### ISSUE TITLE
[Docs] Documentation is a bit misleading

### ISSUE THREAD

**Issue by innub** [UTDNebula/nebula-api#112]
## Docs

- Go version: 1.19
- OS: Ubuntu 22.04

https://github.com/UTDNebula/nebula-api/blob/39701080f05a10508c6f7e65ce40c0ac5e41be1d/docs/index.md?plain=1#L24-L31

It says to place the ``.env`` file inside the ``api`` folder, but then says to run the server one directory above: ``go run api/server.go``. The env loader, [godotenv](https://github.com/joho/godotenv), defaults to the ``.env`` in the root directory, which it assumes is the directory you build from. 

If you follow the docs word for word you get some error like: 
```Error loading .env file: %vopen .env: no such file or directory```

So the docs should read something like
```shell
cd api
go run server.go
```

 Hopefully this doesn't come off as nitpicky as I think this can genuinely confuse people who aren't familiar with how env files are loaded.
 
 :heart:

**Comment by AdamMcAdamson** [comment]
Good catch! I have opened #113 to correct this.
