### ISSUE TITLE
Nebula Data Portal

### ISSUE THREAD

**Issue by johnnyschneider** [UTDNebula/nebula-api#12]
As a student of UT Dallas, or any individual intending to audit historical course data, I can use a portal interfacing directly with Nebula Data Service that provides precisely requested data in a programmable binary formats (JSON, CSV, etc) available for download, per the schema [found here](https://github.com/acmutd/nebula-data-service/discussions/10#discussioncomment-1382683)

**Comment by WillieCubed** [comment]
Closing for now as the scope of this issue is too large to be addressed in a single PR.
