### ISSUE TITLE
Degree Requirements Data Entry Tool

### ISSUE THREAD

**Issue by AdamMcAdamson** [UTDNebula/nebula-api#129]
The Scope of our degree requirement data entry is far too large. Taking 30-60 minutes per degree requirement, with 140 degrees by 4-6 years, we are looking at 500+ man-hours of data entry. This is simply not realistic.

While we wait on getting a better data source from advising (thank you Ryan and Eric for pushing for this), we would like to have 10+ of the most popular degrees, over the past 4 years. 

We can potentially offload a lot of this work to 3162 students in the coming weeks, but we still need to make their throughput much higher.

So, a tool which can take the data from its currently scraped form (of every course listed as course requirements in a single collection requirement), to the final set of collection requirements would be ideal.

So, we have to:
- [ ] Create a tool to ease data entry, which handles:
    - [ ] Collection requirement hierarchy
    - [ ] Inserting other requirement types

**Comment by hochladen** [comment]
Working on this.
