### ISSUE TITLE
[Feature Request] Create class sections API endpoint

### ISSUE THREAD

**Issue by CharlieMahana** [UTDNebula/nebula-api#15]
Create an API endpoint for querying sections in the form `/sections/id` and `/sections/search?property=value` making sure to incorporate proper HTTP status codes.

 - [ ] /sections/id
 - [ ] /sections/search?property=value
 - [ ] Write sections API documentation

**Comment by heartgg** [comment]
See https://github.com/UTDNebula/nebula-api/commit/238bb974e12a7212e84ecd9c599613188b64eef7 for `/sections/id`

See https://github.com/UTDNebula/nebula-api/commit/b124de45944f2ee3579b8945e90df36f88093675 for 'sections/search?property=value`

**Comment by CharlieMahana** [comment]
@heartgg take the code for both sections and middleware and place them into their own directories/files. Have a directory dedicated to middleware as well as having distinct files for each endpoint makes maintaining the codebase far easier as it grows in size. You should them import the code where necessary.

Additionally, please provide documentation for the endpoints in docs.

**Comment by heartgg** [comment]
@CharlieMahana 
I have implemented the above. However, I wasn't sure how to have separate files for each endpoint, so I ended up using routers for each umbrella endpoint (i.e. sections has its own router file, and courses will have a separate file as well).
