### ISSUE TITLE
Student Organization Data

### ISSUE THREAD

**Issue by AdamMcAdamson** [UTDNebula/nebula-api#159]
We would like to provide student organization data as part of our API.

To this effect, we need to:

- [ ] Extend our database schema to include Student Organization Data data (I suggest discussing with Jupiter for their considerations on the matter).
- [ ] Create a Golang model conforming to the schema
- [ ] Develop a scraper with [chromedp](https://github.com/chromedp/chromedp) to scrape the data available from https://soc.utdallas.edu/ -> "Explore Organizations"

**Comment by TortCode** [comment]
im going to try to take the scraper up

**Comment by kneevin** [comment]
hey! is this issue still unresolved? if not, i'd like to try to take a stab at this issue.

**Comment by AdamMcAdamson** [comment]
This ended up getting pushed to https://github.com/UTDNebula/api-tools/pull/1
@TortCode found an existing data source, so we just needed to parse a CSV instead of building out a scraper.

Also, we are in the middle of a repo reorganization, and haven't gotten around to updating the issues to the correct repos.
