### ISSUE TITLE
API Logging

### ISSUE THREAD

**Issue by AdamMcAdamson** [UTDNebula/nebula-api#165]
[To be outlined]

[Ahad's outline]
Currently, the logging coming out of the API is insufficient. We are getting some logs through gin, however, they are not structured or standardized with any other console outputs in the API. To remedy this, I suggest I following progression for API logs.

1. Log requests and API messages to Stdout/Stderr in a consistent, structured way. I suggest emitting information using JSON.
2. Send those logs to a Mongo database in order to leverage them for metrics and to assist with debugging.

Proposed Acceptance Criteria:
1. Log every time a request is made to the API. We should see the method, url, relevant parameters, and any other relevant information.
2. Log critical events in the lifecycle of the API program. For example, we should log when and where (what port) the server is listening, when we have a successful connection to the database, or any other crucial events important for debugging.
3. Errors are not logged within the API packages, rather they are logged in the uppermost layer. This includes either the main function in server.go or in any of the controllers.

Potential Pitfalls/Tips
1. Avoid using too many log levels, I would suggest using only three: Error, Info, and Debug. Maybe panic when a panic should occur.
2. Might want to consider using a logging package. Zap seems to be the most well known, however, there might be others. Maybe there is a log that has built in support for pushing logs to a database?

**Comment by jpahm** [comment]
Complete via #172
