### ISSUE TITLE
Documentation needs to be updated to reflect schema changes

### ISSUE THREAD

**Issue by jpahm** [UTDNebula/nebula-api#180]
The schema has had to change a bit due to the addition of course versioning, and is likely outdated in some other regards as well. It'll need to be updated to reflect the current state of the API.

**Comment by TortCode** [comment]
I can work on this. I might need some sample data to put examples for each field down.

**Comment by jpahm** [comment]
> I can work on this. I might need some sample data to put examples for each field down.

Sounds good. I'll be making some data available on the Discord soon for development purposes, including the actual files as well as a MongoDB URI.
