### ISSUE TITLE
Fix unmarshalling for courses

### ISSUE THREAD

**Issue by jpahm** [UTDNebula/nebula-api#191]
As a side effect of #178, course requirements are no longer being unmarshalled from BSON properly. 

As an example of this, consider the course with the ID `64fe5b032571ddc750fbec5b`, which has prerequisites that look like so:

```json
 "prerequisites": {
        "type": "collection",
        "name": "REQUISITES",
        "required": 1,
        "options": [
          {
            "type": "course",
            "class_reference": "000061",
            "minimum_grade": "C"
          }
        ]
      }
```

However, due to the aforementioned unmarshalling issue, the API now returns the prerequisites in this form:

```json
 "prerequisites": {
        "type": "",
        "name": "REQUISITES",
        "required": 1,
        "options": [
          [
            {
              "Key": "type",
              "Value": "course"
            },
            {
              "Key": "class_reference",
              "Value": "000061"
            },
            {
              "Key": "minimum_grade",
              "Value": "C"
            }
          ]
        ]
      }
```

We will need to find a way to fix this issue, which from my investigation so far seems to require a custom unmarshaller for `CollectionRequirement` in [requirements.go](https://github.com/UTDNebula/nebula-api/blob/develop/api/schema/requirements.go).

Accomplishing this will require referencing [the mongo BSON docs](https://pkg.go.dev/go.mongodb.org/mongo-driver@v1.12.1/bson#Structs) as well as [the mongo package itself](https://pkg.go.dev/go.mongodb.org/mongo-driver/mongo).

**Comment by ahshabbir** [comment]
This could be solved easily by defining a model for Options. Is this not possible? Also I thought that collection requirements consisted of other requirements, is this no longer the case?

**Comment by jpahm** [comment]
Unfortunately, it's not that simple. The "Options" property *is* the set of other requirements that exist within the collection requirement. In this case, the prerequisites are represented by a collection requirement that contains 1 course requirement.

The issue here is not a lack of models, rather, it's directly tied to how Gin, and Go itself, for that matter, handle unmarshalling by default. There is no way to make a generalized model for the contents of "Options" because they can consist of any type of requirement.
