### ISSUE TITLE
Relocate GraphQL API to different branch

### ISSUE THREAD

**Issue by jpahm** [UTDNebula/nebula-api#212]
Currently, the dev branch has a `graphql` directory containing a (somewhat outdated now) GraphQL-based implementation of the API. While this could be useful to transition to at a later point, using GraphQL is not currently a priority nor is it a clean change to make.

As such, it would make sense to move this directory to its own separate branch and then remove it from the dev branch.

- [ ] Remove `graphql` directory from dev branch
- [ ] Transition `graphql` directory to its own branch

**Comment by mikehquan19** [comment]
Hi! I'd like to work on this but I have a few questions to clarify. Are we supposed to create another branch which we will keep the ```graphql``` directory and then we will remove ```graphql``` in the branch develop?

Thanks.

**Comment by jpahm** [comment]
> Hi! I'd like to work on this but I have a few questions to clarify. Are we supposed to create another branch which we will keep the `graphql` directory and then we will remove `graphql` in the branch develop?
> 
> Thanks.

Hi, yes, that's correct! You can go ahead and merge the GraphQL branch you make into [this](https://github.com/UTDNebula/nebula-api/tree/graphql) branch. Ideally, the GraphQL branch should exclude the current API (in the `api` dir) and the non-GraphQL branch should exclude the GraphQL API (in the `graphql` dir).

**Comment by jpahm** [comment]
Finished via #220 and #221.
