### ISSUE TITLE
Remove deprecated docs/endpoints

### ISSUE THREAD

**Issue by jpahm** [UTDNebula/nebula-api#213]
The API currently contains a few deprecated docs and endpoints referring to features that are no longer planned. These include the following:

- Course credit data
- Degree data
- Exam data

The following work must be done:

- [ ] Remove/update documentation that refers to these features
- [ ] Remove any endpoints/controllers/etc. that exist for these features

**Comment by greeshiee** [comment]
Is this issue still open? I'd like to try working on it!

**Comment by jpahm** [comment]
Closed via #222
