### ISSUE TITLE
Change autocomplete endpoint to pull from "DAG" database view

### ISSUE THREAD

**Issue by jpahm** [UTDNebula/nebula-api#225]
Currently the `autocomplete` endpoint performs an aggregation within the controller itself, putting together a new aggregation pipeline for each request. As this is relatively inefficient and messy, the aggregation pipeline for this has instead been added to the database itself as a view called `DAG`. 

The controller should be modified to pull results from this view instead of generating the pipeline itself.

**Comment by mohammadmehrab** [comment]
Can I be assigned this?

**Comment by jpahm** [comment]
Sure thing!

**Comment by jpahm** [comment]
Closed via #233
