### ISSUE TITLE
Add "sections" aggregate endpoint to course endpoint

### ISSUE THREAD

**Issue by jpahm** [UTDNebula/nebula-api#227]
Currently, it can be inconvenient and overcomplicated for our end users to perform some common aggregate operations such as getting all of a course's sections.

As such, we should add the following endpoints which immediately aggregate and return matching courses' sections:
- Query based: `GET /course/sections` (allows for querying like the base course endpoint)
- ID specific: `GET /course/{courseId}/sections` (gets sections only for a specific course)

**Comment by mikehquan19** [comment]
Can I be assigned this ? This is fun.

**Comment by jpahm** [comment]
> Can I be assigned this ? This is fun.

I'm glad it's fun, the work on these issues is very helpful!

You are good to work on it :)

**Comment by mikehquan19** [comment]
I completed this task and committed it in the same pull request as task #230. 
Thank you.
