### ISSUE TITLE
Add "courses" aggregate endpoint to professor endpoint

### ISSUE THREAD

**Issue by jpahm** [UTDNebula/nebula-api#230]
Currently, it can be inconvenient and overcomplicated for our end users to perform some common aggregate operations such as getting all of a professor's courses.

As such, we should add the following endpoints which immediately aggregate and return matching professor's courses:
- Query based: `GET /professor/courses` (allows for querying like the base professor endpoint)
- ID specific: `GET /professor/{professorId}/courses` (gets courses only for a specific professor)

**Comment by mikehquan19** [comment]
Can I work on this? I want to practice querying the MongoDB database and building API a bit more.

**Comment by jpahm** [comment]
> Can I work on this? I want to practice querying the MongoDB database and building API a bit more.

You're more than welcome to!

**Comment by mikehquan19** [comment]
Hi! I've made the pull request. Hope you will review it and give me feedback.

Thank you.

**Comment by jpahm** [comment]
Thanks, I will review it shortly!

**Comment by mikehquan19** [comment]
Hi @jpahm, I've fixed the problem about options limit, so I just want to let you know in case you haven't been aware of it yet.
Thank you.

**Comment by jpahm** [comment]
> Hi @jpahm, I've fixed the problem about options limit, so I just want to let you know in case you haven't been aware of it yet. Thank you.

Thank you, I will take a look!
