### ISSUE TITLE
Add CORS to API

### ISSUE THREAD

**Issue by CharlieMahana** [UTDNebula/nebula-api#25]
Modify the API so we fit the CORS specification.

**Comment by WillieCubed** [comment]
Could you be more specific? What is the CORS spec you're talking about, and why does it matter? How would we go about implementing this in our project?

**Comment by CharlieMahana** [comment]
Cross-Origin Resource Sharing (CORS) is an HTTP-header based mechanism that allows a server to indicate any origins (domain, schema, or port) other than its own from which a browser should permit loading resources. Since our API will be used on projects other than our own, we must meet the CORS spec so that applications dependent on our API from other domains can properly load data. 

Requirements:
- Include CORS headers where appropriate (endpoints available to the public)
- Fully support CORS preflight requests (headers, methods, caching, etc)
- Fully support "credentialed" CORS requests to enable domain restrictions

The [Mozilla Docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) have some great information on CORS. Please thoroughly read the documentation.
