### ISSUE TITLE
API Token Authentication

### ISSUE THREAD

**Issue by CharlieMahana** [UTDNebula/nebula-api#28]
In order to regulate public usage of the Nebula API, we need to require that those who query data have to provide an authentication token. This will enable us to rate limit specific users, monitor usage, and give us greater control over system usage to name a few benefits. 

**Tasks**
- [ ] Enable the creation and destruction of API tokens that reference the owner. Manual token activation and moderation is okay. 
- [ ] Develop middleware that checks the Authorization HTTP header of a request for an authentication token. In the case that a token either does not exist or is inactive, return an appropriate error.

**Comment by heartgg** [comment]
How manual can the token moderation be? Is it fine to directly make tokens and insert them into the database, or should there be an interface for authorized users (perhaps part of the Nebula Data Portal) that allows for token moderation?

**Comment by CharlieMahana** [comment]
Creating tokens can be manual insertions into the database for the time being. Eventually, the process of creating and destroying tokens should be accessible from an admin portal, but we'll look at doing that much much farther down the road.
