### ISSUE TITLE
API Token Rate Limiting

### ISSUE THREAD

**Issue by CharlieMahana** [UTDNebula/nebula-api#30]
In order to ensure the health and accessibility of the Nebula API, we will need to reasonably document API usage in order to develop adequate usage metrics. Using these metrics alongside rate limiting will enable us to ensure optimal API performance, regulate infrastructure costs, and enforce proper API usage. 

**Tasks**
- [ ] Enable the storage of each API token's usage including the cumulative number of requests made during the current hour and the API token's maximum number of requests per hour. 
- [ ] Develop middleware that verifies that the number of requests made hasn't exceeded the quota, updates the number requests made after every request, and returns the number of requests made, the number of requests left, and the maximum number of requests per hour in the HTTP Headers.

**Comment by WillieCubed** [comment]
Closed by #39

**Comment by WillieCubed** [comment]
According to @heartgg, apparently this wasn't implemented.
