### ISSUE TITLE
Scrape all data from Course book

### ISSUE THREAD

**Issue by TrystonMinsquero** [UTDNebula/nebula-api#62]
As the code for this is pretty much done, this mainly consists of updating the data into the form of the schema.

**Comment by hochladen** [comment]
I have work on this already underway, though some components of it (i.e. the prerequisite/corequisite parsing) are extraordinarily complex and may take a considerable amount of time. I'll keep this issue updated with any developments.

**Comment by hochladen** [comment]
Parsing is pretty much fully functional and I've started to do the final data scraping.
