### ISSUE TITLE
Scrape all Exam data from Catalog

### ISSUE THREAD

**Issue by TrystonMinsquero** [UTDNebula/nebula-api#66]
We need to be able to scrape from the catalog for exam course equivalences

- [ ] [AP](https://oue.utdallas.edu/undergraduate-advising/ap-credit)
- [ ] [CLEP](https://oue.utdallas.edu/undergraduate-advising/clep-credit)
- [ ] [IB](https://oue.utdallas.edu/undergraduate-advising/ib-credit)
- [ ] [ALEKS](https://oue.utdallas.edu/aleks-exam)

Some of these are so small they could be done by hand (Especially ALEKS), but it would be nice to have a scraper to use for the future if anything were to change. However, if there is difficulty and it can't be done before Monday 3/14/2022, please just do it by hand.

This is for @AdamMcAdamson

**Comment by AdamMcAdamson** [comment]
I think I'm not entirely caught up on how we are establishing the Course ObjectIds.

I've been assuming they will be generated. If that is the case, then we will have to employ a separate script to build the associations between courses as outlined here (with prefix/number combinations) and their respective ObjectIds in the database, as they will be deployment/cluster specific.

If this is not the case, can you point me to the strings we are basing the ObjectIds off of?

Even so, I think this data should be separate from implementation specific details on that level, as this is still in active development.
